---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: us-central1-docker.pkg.dev/team-simulation-project/cloud-deploy-image/docker-image-cicd
        ports:
          - containerPort: 5000
