---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world
spec:
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
  selector:
    app: hello-world-app
